### ISSUE TITLE
Wine is tiled if not fullscreen

### ISSUE THREAD

**Issue by 4n0nct** [lingtjien/Grid-Tiling-Kwin#119]
1/ It happens also with popups which are here to prelaunch a game, it will tile.
Imagine that tiny windows which just make you select a res and vsync, it should be really tiny, but then it will take all the screen, and making it "float" on the fly won't make it take its real size, it will still occupy all the screen.
wine and wineserver are in the ignored_list.

2/ After a game at low resolution is terminated, if the desktop doesn't return to its real resolution (it happens a lot), when I make a
xrandr -s 1920x1080
then the windows (for exemple: terminals) are not tiled anymore but floating.

3/ In the UI options there is a setting with a lot of 2,2,2,2,2,2,2,2,2,2,2,2,2,2
Will you clarify that ? I just don't understand what I'm looking at and how to interact and what it does

Thank you for your future answers.

**Comment by lingtjien** [comment]
1. You can ignore clients by expanding the ignored name regex (or caption) so that they are never tiled. In order to find the correct name of the client that you want to ignore you could open the client menu and then `More Actions` -> `configure special application settings` and in the window class box you'll find the name that you need to match with the regex
2. What happens if you use the global shortcut `Grid-Tiling: Refresh`?
3. See #115

**Comment by 4n0nct** [comment]
Oh thx, didn't see you've answered, I will look at that.

**Comment by lingtjien** [comment]
Assuming, it's fixed by now. Otherwise you can open a new ticket 😄
