### ISSUE TITLE
Gtk app menu is tiled

### ISSUE THREAD

**Issue by pasqui23** [lingtjien/Grid-Tiling-Kwin#122]
As shown in https://github.com/NixOS/nixpkgs/issues/145274 the app menu for (only) gtk app menu is tiled when it should not

**Comment by lingtjien** [comment]
I believe this is because Wayland does not have a concept of window types. Back in X11 we had window types according to the opendesktop standard. So back in the X11 version of this script I also used these window types to not tile certain windows if they were not a normal application. As according to the spec at  https://specifications.freedesktop.org/wm-spec/wm-spec-latest.html
```
_NET_WM_WINDOW_TYPE_DESKTOP, ATOM
_NET_WM_WINDOW_TYPE_DOCK, ATOM
_NET_WM_WINDOW_TYPE_TOOLBAR, ATOM
_NET_WM_WINDOW_TYPE_MENU, ATOM
_NET_WM_WINDOW_TYPE_UTILITY, ATOM
_NET_WM_WINDOW_TYPE_SPLASH, ATOM
_NET_WM_WINDOW_TYPE_DIALOG, ATOM
_NET_WM_WINDOW_TYPE_DROPDOWN_MENU, ATOM
_NET_WM_WINDOW_TYPE_POPUP_MENU, ATOM
_NET_WM_WINDOW_TYPE_TOOLTIP, ATOM
_NET_WM_WINDOW_TYPE_NOTIFICATION, ATOM
_NET_WM_WINDOW_TYPE_COMBO, ATOM
_NET_WM_WINDOW_TYPE_DND, ATOM
_NET_WM_WINDOW_TYPE_NORMAL, ATOM
```

I have asked the KWin developer what the best way to deal with this problem in wayland was https://github.com/lingtjien/Grid-Tiling-Kwin/issues/78 and implemented that by checking for transientFor. But the application developer has to properly set this so KWin knows it's not a regular application.

**Comment by lingtjien** [comment]
I finally had some spare time again and did some digging in KWin and I found some changes since last time I checked it. It seems that they support windows types in wayland as well now. So I added the support for it in the dev branch. Give it a try, by default it will now only tile windows of type `normalWindow` but I made it user configurable.

**Comment by lingtjien** [comment]
Fixed by adding property ignores
