### ISSUE TITLE
Cannot move windows to other virtual desktops

### ISSUE THREAD

**Issue by jlemonde** [lingtjien/Grid-Tiling-Kwin#131]
Dear lingtjien, 
I'm absolutely loving your implementation! 

However I experience a bug that impedes me from moving some windows around. 
I am hereby uploading a short video in which I am trying it in three different ways: by right clicking the status bar > `move to desktop` > `N: desktop name`; then by drag-dropping the window in the main panel's widget, and finally by drag-dropping from the official desktop grid effect. Note that I also tried global shortcuts: these don't work for me either...

I hope that there will be an easy fix! Thank you!

https://user-images.githubusercontent.com/30623792/191234336-302466de-6acd-4a7b-b6c2-d504cfec9560.mp4

Operating System: Ubuntu 22.04
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.3
Kernel Version: 5.15.0-47-generic (64-bit)
Graphics Platform: X11
Processors: 8 × Intel® Core™ i5-10210U CPU @ 1.60GHz
Memory: 15.3 Gio of RAM
Graphics Processor: Mesa Intel® UHD Graphics
Manufacturer: LENOVO
Product Name: 20U9008FMZ
System Version: ThinkPad X1 Carbon Gen 8

**Comment by lingtjien** [comment]
Have you tried restoring the default settings?

Also, could you add a picture of the `KWin` shortcuts section on your system (and filter by `Grid-Tiling`). So we can verify that the correct shortcuts have been assigned

**Comment by jlemonde** [comment]
It was indeed the first time I've tried that script. And I also disabled all other kwin scripts to try this one out.
I did not set the keyboard shortcuts at all, though, as some of them were already in use for other purposes. 
I was planning to set a few later on. 
Why are you asking? Is the implementation relying on the keyboard shortcuts being set to specific values? Because I probably won't conform with the default shortcuts. The global shortcuts I was talking about in my previous message were those to move a window directly to another numbered virtual desktop.
Thank you very much!

**Comment by lingtjien** [comment]
The implementation doesn't care which shortcuts you assign, and since you're not having any success with any method of moving clients between virtual desktops it's probably not related to the shortcuts. (you are free to use any shortcuts you like for the global shortcuts)

So could you please do the following steps:
1. use the restore defaults button in the kwin script settings section of this script
2. reboot computer
3. open terminal on virtual desktop 1
4. move this terminal to virtual desktop 2
5. if that doesn't work, open another 11 terminals and describe (or show) what happens

**Comment by lingtjien** [comment]
I'm going to assume you've found the problem. If not then please create a new ticket (with a minimal working example in a clean environment to reproduce)
