### ISSUE TITLE
Plasma are crashed

### ISSUE THREAD

**Issue by gratural** [lingtjien/Grid-Tiling-Kwin#137]
Hello. 
I have a serious trouble. Sometimes Plasma crashes and closes all open applications. Sometimes it happens when I open a new window and sometimes when I close it. 
As I understand it, it mostly happens when I have more than 5 windows opened on multiple virtual desktops.

My config:
OS: Manjaro Linux x86_64
Kernel: 6.1.23-1-MANJARO
Resolution: 2560x1080 
DE: Plasma 5.27.4 
GPU Driver: amdgpu
Wayland

Maybe I didn't set up the script correctly?

This problem did never happen on the bismuth with KDE 5.26.
My error log and kwin config are attached.

[die_plasma.log](https://github.com/lingtjien/Grid-Tiling-Kwin/files/11238446/die_plasma.log)
[kwinrc.md](https://github.com/lingtjien/Grid-Tiling-Kwin/files/11238453/kwinrc.md)
..upd..
[i_just_open_second_firefox_tab_in_new_window.log](https://github.com/lingtjien/Grid-Tiling-Kwin/files/11238487/i_just_open_second_firefox_tab_in_new_window.log)

**Comment by lingtjien** [comment]
Are you sure this is caused by this script and not by something else? Also, I can't really fix a problem if I can't reproduce it consistently, so I kind of need a step by step of how to produce the crash that you are referring to.

You could try to use default settings and changing settings one by one until crashes happen, in order to figure out what is causing it.

Besides, if a KWin script crashes it should just turn the script off, that shouldn't lead to KWin crashing. If it does then there is a bug in KWin.

> Maybe I didn't set up the script correctly?

If you followed the instructions and your windows are being tiled then it should be fine.

**Comment by lingtjien** [comment]
due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
