### ISSUE TITLE
Plasma 6.0.2 Breaks this scrip

### ISSUE THREAD

**Issue by AntoineBalaine** [lingtjien/Grid-Tiling-Kwin#139]
Hello, does anybody know what's up with the latest plasma Desktop update?

The script is simply not being detected anymore by the system, and all the display settings prior to the update are broken. I tried re-installing the script and it just won't work.

Does anyone know a fix for the new plasma version?

**Comment by lingtjien** [comment]
I will check it out, I haven't upgraded to plasma 6 myself yet. I'm always hesitant with big major releases

**Comment by AntoineBalaine** [comment]
Haha, fair enough! Good luck with the update.

**Comment by lingtjien** [comment]
Small update, working on it, Plasma 6 seems to have revamped a very large part of the API, so this is going to be a big change and require some time and I will take this opportunity if I'm going to make such big changes anyways to do some refactoring.

If any of the KWin devs read this, So far the changes that were made to the API seem to improve the API in general so 👍 , documentation is lacking but the source code is well commented so that works fine for me (prefer to read well documented code anyways).

I've marked the current master as plasma5 for now and will be working on the dev branch for plasma 6 support (doing a lot of commit overwrites currently, so I'm not pushing to github yet while actively refactoring and just pushing to my own local server)

**Comment by AntoineBalaine** [comment]
Lovely, thank you very much!

**Comment by felixwoolford** [comment]
Thanks for the effort! I'm using an alternative in the meantime and it is making me appreciate this script all the more

**Comment by OnlyLys** [comment]
I've tried a lot of tiling extensions and this one is still the best. Looking forward to it working in Plasma 6.

**Comment by lingtjien** [comment]
Small update:

Have refactored most of the code base using the new KWin API in Plasma 6. Only need to hook up multiscreen support and  the configuration needs to be redone a bit due to the new API requirements (currently hardcoded to 2x2 grid). I've only been testing in wayland using a single screen.

Will be doing more testing the coming week, try adding multiscreen support and fix the configuration

**Comment by lingtjien** [comment]
Done, you may consider the current `develop` branch as a first alpha release.

Script has been adapted to new Plasma 6 KWin API. Almost all functionality has been ported, I've dropped a few of the the shortcuts that had no default binding and adapted the behavior of some others, I believe for the better, but this is after all an opinionated script (if you really miss a specific shortcut or behavior then let me know down below and I'll see what I can do).

Only thing left is to update the `README.md` file, so I'll do that the coming week and fix more bugs if I or you guys come across them. So basically you have until next week to give it a try :smile: before I merge it back into master (unless I come across big show stoppers, that require big changes).

(FYI: I'll be going on a long weekend holiday this week so I'll be busy with other things as well)

**Comment by AntoineBalaine** [comment]
Just tested it, and everything seems to be working good.

I'm getting some issues with system setting's window placement:
 
![overlay_grid-tiling](https://github.com/lingtjien/Grid-Tiling-Kwin/assets/54488126/e473b0b2-5d4c-4622-a0f8-5e79c1cc1dec)
System settings window always seems to be bigger than the frame size you'd expect it to have.

Other than that:
- Adding shortcuts to your script in system settings has some bugs: I'm having to add two shortcuts to the same action, apply, and then delete the second one to get the first one working. I assume that's a KDE bug, though.
- the list of shortcuts from the script's previous version is still in the actions' list, though the script isn't there anymore - I dunno if this has anything to do with the update.

Config UI grid tab: 
Where is this? I can't find it in the system settings.

Feature request:
- a config file to black list some apps from tiling. This is useful for screen-captures: you'd open `spectale` or some screen-cap utility, and it wouldn't jumble-up the tiles on screen.

Thank you very much for putting together this update! Do you have a link where we can buy you a coffee?

**Comment by OnlyLys** [comment]
Thank you @lingtjien.

I'm so far having no issues with the [latest `develop` tip](https://github.com/lingtjien/Grid-Tiling-Kwin/commit/310589d3920faea00caf0ae7fcdbad4aba8d00d1), however is it possible to add a shortcut to disable automatic tiling that we had before?

**Comment by OnlyLys** [comment]
@AntoineBalaine 

> Config UI grid tab:
> Where is this? I can't find it in the system settings.

I believes he means the settings page of the extension which you can access in KDE's KWin Scripts setting page, accessible through `System Settings > Window Management > KWin Scripts`. There you can also blacklist or whitelist apps.

**Comment by AntoineBalaine** [comment]
@OnlyLys  Thanks for the pointer! Black list works wonders - yet another proof that I should be more diligent about reading instructions…

**Comment by lingtjien** [comment]
I have updated the readme with the latest information. Also made a small refactor after I had a good ideas while going for a run and fixed a few more bugs. Happy to hear you guys haven't had major issues yet.

> System settings window always seems to be bigger than the frame size you'd expect it to have.

That is because as far as my understanding goes, some windows in wayland can force their minimum sizes, so I can not change the geometry of those windows beyond that. Easiest solution is to just add to applications to a larger `minSize` in the configuration. (I've had the same problem and added system settings to the default configuration)

> Adding shortcuts to your script in system settings has some bugs: I'm having to add two shortcuts to the same action, apply, and then delete the second one to get the first one working. I assume that's a KDE bug, though.

I had similar problems, with setting global shortcuts they didn't want to register for some reason the first time. This is completely beyond this script, this script only registers a few global shortcuts. How to set them is not done by me.

> the list of shortcuts from the script's previous version is still in the actions' list, though the script isn't there anymore - I dunno if this has anything to do with the update.

There is a section in the readme regarding this issue

> Thank you very much for putting together this update! Do you have a link where we can buy you a coffee?

If you really want, I added a paypal donation button at the bottom of the new readme, wanted it as small and far away as possible to indicate that it is completely optional. But thank you nonetheless, I could use that to renew my domain or buy some snacks during my upcoming trip to Japan :smile: 

> however is it possible to add a shortcut to (temporarily) disable automatic tiling like we had before?

Oh woops seems I already ported the code but forgot to define the shortcut. Will do

**Comment by AntoineBalaine** [comment]
Great, thanks for making this update. I made a small donation. Let me know if you want me to close this issue.

**Comment by lingtjien** [comment]
Thank you very much,

> Let me know if you want me to close this issue.

I will close this issue myself once I merge it back into master. I will then also close all the other old tickets as they were all made during plasma5.

**Comment by lingtjien** [comment]
> however is it possible to add a shortcut to (temporarily) disable automatic tiling like we had before?

Added

**Comment by OnlyLys** [comment]
@lingtjien Thank you!

**Comment by lingtjien** [comment]
has been merged to master, you can create new tickets if you encounter issues in Plasma 6
