### ISSUE TITLE
Move to Desktop (from action menu) does not work

### ISSUE THREAD

**Issue by dim-geo** [lingtjien/Grid-Tiling-Kwin#20]
Hi,

When you click window's action menu and move the window to a specific desktop, refresh action brings it back.

Grid tiling should grab the signal that the window has changed desktop and treat it appropriately.

On a general note:
It would be nice to add some comments into the source code, or elaborate more in order to help others to help you.

Thanks a lot for your efforts!

**Comment by lingtjien** [comment]
I have tried to implement this, by connecting to the kwin signals directly and handling those, which would also allow me to get rid of all my custom shortcuts to move clients between desktops. But if I remember correctly, I was unable to actually change the geometry of anything in this callback (I suspected that this callback was executed before the geometry was changed, thus changing the geometry back after).

I'll give it another try when I find some time.

**Comment by dim-geo** [comment]
Please check my pull request #21. The first commit from this branch theoretically could support this but it conflicts with move to desktop shortcuts. Could you please make them use the signal handing somehow...?

As a workaround I added extra shortcuts in commit 2: Move a window to desktop without switching desktop as well...

**Comment by lingtjien** [comment]
I checked your commit and I think you're on the right track, I didn't see the desktopPresenceChanged() in the API reference myself yet so that might be the solution to the problem. I tried to hook into the client signals desktopChanged() but this one didn't work due to previously mentioned problems.

I'll give it another try with the desktopPresenceChanged() API.

Thank you for the idea (I'll keep you updated, should have some time this week in the train to work on it).

**Comment by lingtjien** [comment]
I think I fixed it, it's in the developer branch now. There are a few things to note though

1. The support for regular KWin shortcuts for moving clients between virtual desktops and screens should work now so I removed the ones from this script as you can now just use the default ones.
2. using the action menu or dragging windows from one virtual desktop into the other using the panel or the grid view does work correctly internally in the script but for some reason, KWin does not render it correctly. It only renders the width and height of the client correctly but it always puts it at x=0 and y=0 even if I specify a specific value, you can hit the refresh shortcut and it should render the window correctly. (I will have to do some more testing later to see if it's not something I'm doing wrong or it's something with KWin).
3. I provided a shortcut to move clients to the next virtual desktop or screen depending on the current virtual desktop or screen (example: if you have 2 screens with 4 virtual desktops, `1 client` open on `screen 1` `virtual desktop 1` and you press this shortcut it will move the client to `screen 2` and `virtual desktop 1`, press it again and it should move it to `virtual desktop 2` and `screen 1` then `screen 2` and `virtual desktop 2` etc...)

**Comment by lingtjien** [comment]
4. ReadMe will need some rewriting now, but I would like to implement the floating/tile shortcut first before I do that since that one has been long requested #8 and after that and some more testing I'll merge it back into master.

**Comment by lingtjien** [comment]
> I am dabbling with KWin scripting and I found a similar issue - I can not change `client.geometry` within a `desktopPresenceChanged` signal, the client keeps the original geometry.

I could change the width and the height property of the geometry, but I couldn't change the x and y values. (If I remember correctly)

> I have found an ugly workaround that works consistently for me

I'm not a fan at all of any workarounds, unless it hinders the user experience to such a level that it becomes downright annoying for the user (and also depending on the hackiness of the workaround). In this case I think the displacement on using the action menu to move clients between desktops inconvenience does not outweigh the hackiness of the solution. Maybe we should open a ticket in KWin bugzilla so they can try to fix it, because I believe it's a problem with KWin. 

The API also gives you the ability to do the same as `desktopPresenceChanged` with `desktopChanged()` in the client signals, which I used first but that one has the same problem as the other one, last time I checked.

But I didn't know about the QTimer so that's usefull to know, since there is no setTimeout available.

Anyways, thank you for taking the time to let me know about your findings and solutions. Suggestions are always welcome

**Comment by lingtjien** [comment]
> having to do the refresh shortcut every time would be annoying for me
hmm you have a point there but the solution is really hacky so I'd rather have it fixed upstream...

> We should, do you have time to do so maybe?
I made a small demonstration example and reported it, let's see what they do with it https://bugs.kde.org/show_bug.cgi?id=403172

>  do you know how you can see print outputs anywhere
Personally, I use the interactive console exclusively (since it serves the purpose okayish for now, minus the bug with printing) but there is another way that someone has mentioned in one of my other bug reports (regarding the interactive console) https://bugs.kde.org/show_bug.cgi?id=392840 using the KDebugSettings (I haven't tried it, but according to others it seems to work better since it doesn't have the printing bugs that the interactive window has)
