### ISSUE TITLE
Issue resizing window

### ISSUE THREAD

**Issue by RaitaroH** [lingtjien/Grid-Tiling-Kwin#24]
Not sure what is causing this but, I can't resize any window. If I try I get some tearing like in windows frozen program, but the size of the windows is the same. I have `enforce window decorations on gtk+ window`, `grid tiling` and `MinimizeAll` scripts activated. I thought perhaps `Sticky Window Snapping` was the cause but doesn't seem to be it because I have disabled it (restart system, and kwin separately)...
 
I also mention that the kwin global shortcuts for this script do not work either.

**Comment by lingtjien** [comment]
What happens when you do the following:

1. Turn off all other scripts and turn on this script only
2. Open global shortcuts and go to the KWin section and search for `Grid-Tiling: Increase Size` and check if it is assigned to a keybinding.
3. Do a reboot (so we're sure it's a clean start)
4. Start up two terminals on the same desktop
5. Then try to resize the windows using the global shortcut that you have assigned to `Grid-Tiling: Increase Size`.

**Comment by RaitaroH** [comment]
I still have the issue.

**Comment by lingtjien** [comment]
Could you do a screen recording to show it? (the following three things: your kwin script menu, global shortcut kwin section and the resizing itself)

You're the first person to report that the basic resizing functionality doesn't work but I am not having any problems at all and neither has anyone else reported this...

**Comment by lingtjien** [comment]
Hmm weird, what happens if you resize by dragging the edges of a window by mouse? Also, what values do you use for `divider bounds` and `divider step size` (in the settings menu)?

**Comment by RaitaroH** [comment]
If I resize with mouse and alt... nothing. I get some horrible distortion but the size is same.

![screenshot_20181127_203643](https://user-images.githubusercontent.com/19552720/49103493-2bd84a00-f284-11e8-986b-bed6f53aa7d6.png)

Other shortcuts work, such as moving the windows. I am not sure why if I have say 50%,25%,25% I can't move a 25% to the other side to be 50%.

**Comment by RaitaroH** [comment]
Resizing. Happens even when I turn off sticky window snapping script
[screencast4.zip](https://github.com/lingtjien/Grid-Tiling-Kwin/files/2621396/screencast4.zip)

**Comment by lingtjien** [comment]
Ahhh... now I see... You removed (set to zero is same) all the values from `divider bounds` `divider step size` and `move threshold` these values are used for resizing and moving windows...

So `divider step size` controls how much a client will change in size when you use the `Grid-Tiling: *Increase/Decrease* Size`. The default is 0.05 so that's 5% of the client's size. Since you set it to 0 the increase and decrease in size when you use the global shortcut is 0%, in other words, it does nothing.

`divider bounds` is the maximum size a client can increase or decrease from 1 side. So if you set it to 0.25 for example, it means that you can decrease (and increase) the size on both sides of a client by 25% so that means that the minimum size a client can become is then 50% (100 - 25 from the left and - 25 from the right). (This values should be normally be set to something between 0 and 0.5.)

`move threshold` determines how far you have to drag the client outside of its current location before a switch is registered. For example, if you set it to 0.5 it means that you have to drag the client at least out of 50% of its current position before it will register a `Grid-Tiling: Switch *direction*` action.

(In the left bottom corner there is a defaults button that will reset all values to default.)

**Comment by RaitaroH** [comment]
Oh, silly me I guess. I set everything to 0 because I didn't like the gaps. It works now though XD
