### ISSUE TITLE
Prioritize Columns over Rows?

### ISSUE THREAD

**Issue by xhizorsz** [lingtjien/Grid-Tiling-Kwin#44]
I'm using the script with a 21:9 Ultrawide and love it. But is there a possibility to prioritize the creation of columns?

I set the grid to 2x3 and as an Ultrawide user its fine to work with the screen split in 3 columns. So my idea is to first create 3 cols and after that begin with splitting the rows.

Is there a option I have overlooked or a quick modification I can do?

**Comment by lingtjien** [comment]
You can modify the method that adds the clients to the desktop (line 362, `addClient` method from the `Desktop` class) to something like this.

```
    var column = new Column();
    if (this.addColumn(column) === 0)
      return this.columns[this.ncolumns() - 1].addClient(client);

    for (var i = 0; i < this.ncolumns(); i++)
    {
      if (this.columns[i].minSpace() + client.minSpace <= 1 / this.ncolumns() && this.columns[i].nclients() < this.maxRows)
        return this.columns[i].addClient(client);
    }
    
    return -1;
```
This attempts to first create a new column and if successful add the client to that column, if this fails loop through all the columns from left to right to check which one has space for the new client and add the client, otherwise signify that this method failed to add the client.

**Comment by xhizorsz** [comment]
Thank you! It works like a charm!
