### ISSUE TITLE
When disconnecting monitor, my windows get dis-tiled

### ISSUE THREAD

**Issue by andrei-pavel** [lingtjien/Grid-Tiling-Kwin#50]
Setup is simple. I have windows tiled on my HDMI monitor. I disconnect HDMI monitor. After the screen settles, all my windows are not tiled anymore and they are overlayed one another. I think it's because of the difference in resolution between the primary monitor and the external one.

Asking to get re-tiled automatically is too much I think. But rather would a shortcut to re-tile them to arbitrary positions be possible? Is this already provided by kwin? I couldn't find any.

Does this happen to nobody else?

One thing I do to re-tile the windows is drag them just a bit and it works, but it's cumbersome and sometimes they're in inaccessible spots fully hidden behind another window and I'm starting to develop monitor disconnect anxiety.

**Comment by lingtjien** [comment]
Have you tried the `Grid-Tiling: Refresh` shortcut?

**Comment by andrei-pavel** [comment]
Refresh makes all the windows occupy space as if there was a single window on the screen. Like fullscreen but with the 8 pixel border that I have. Then, if I walk through windows / alt-tab, one-by-one they start occupying the correct space. So maybe programatically shifting focus through all the windows would work.

**Comment by lingtjien** [comment]
hmm sounds like the clients were removed from the script internally (as in closed) because I use the focus method to add clients to the script internally. I'll take a look when I get access to a second monitor.

Just to clarify, could you fill in the question marks here for me?
1. fresh reboot with 2x2 grid
2. open 4 konsoles on screen 1 virtual desktop 1
3. open another 4 konsoles on screen 2 virtual desktop 2
4. disconnect screen 2
5. ??? (what happens to konsoles 1-4 and 5-8? are 1-4 still correctly tiled and 5-8 wrong, or both?)

**Comment by andrei-pavel** [comment]
I opened 6 Konsoles + another 6 Konsoles with my current 2x3 grid setup.

All of them, 1-6 and 7-12, get moved to screen 1.

Here's a screenshot of how they look:

![image](https://user-images.githubusercontent.com/6838492/68490562-e244fd00-0251-11ea-9843-585502b5ff72.png)

Even though they are jumbled up like that. If I walk through all of the windows, I can take a glance at how they look without modifying their position. And none of them are tiled correctly anymore. If I modify one's position with a simple drag around the screen, then 6 of them get moved to virtual desktop 2, but even then none of them are tiled correctly. I have to move around each and every one of them to end up with a correctly tiled setup. Hope this helps.

This is far better than the other tiling scripts so I'm committed to making this work.

**Comment by lingtjien** [comment]
I took a quick look at it and it seems like I can't do this automatically (without hacking a timer) or haven't been able to come up with an elegant solution. However, as you said doing it manually should work but I can't connect this to the signal that is send when the number of screens is changed because this signal is fired way before the clients are closed, so I would probably need a timer and wait, but then the wait duration would depend on your specific system blablabla.... (in other words, not elegant)

But give the dev branch a try, I added it to the `Grid-Tiling: Refresh` shortcut to always try to re-add all the clients.

**Comment by andrei-pavel** [comment]
Thank you for looking into this. Unfortunately, Refresh-ing on `develop` behaves the same way. I have a hunch that the client is still assigned to the old screen and that's why it can't tile.

My assumption is that a client is a window. Is this correct?

If that's the case, is it possible to do something like `Client.assignToGridCell({virtual_desktop: 1, screen: 1});`. Hopefully, that subsequently fills screens eventually re-assigning windows to random grid cells which is still the same outcome as now for me.

Have you managed to replicate this issue though? Maybe it has to something to do with my setup, like using this script in conjuction with `kwin-dynamic-virtual-desktops`. :man_shrugging:

**Comment by lingtjien** [comment]
yes clients are windows, the API refers to them as clients.

What I was able to reproduce was the following with the last step only working after the change:
1. connect 2nd screen
2. start 4 konsole on first screen (virtual desktop 1)
3. start another 4 konsole on second screen (virtual desktop 1)
4. unplug 2nd screen
5. all windows get send to first screen and only 1 client is tiled (the one you happen to have your mouse on top)
6. global shortcut `Grid-Tiling: Refresh` all konsoles now get tiled, 4 on virtual desktop 1 and the other 4 on virtual desktop 2 both screen 1 (since there is now only 1 screen)

**Comment by andrei-pavel** [comment]
Refresh works as you described.

I was installing the script by copying files manually to a different directory named the same as this repository. `kpackagetool5` does not use the repository's name so and this I originally installed it with `kpackagetool5` so up until now I was using the old version. That was why I didn't see the new behavior.

It's enough for me. I hope this gets into master. Thank you so much! :tada:
