### ISSUE TITLE
Full screen functionality restricted to tile

### ISSUE THREAD

**Issue by j0hannes** [lingtjien/Grid-Tiling-Kwin#54]
Is it possible to limit an application to its tile, so that activating the full screen mode (e.g. a video player) would not occupy the whole screen, but only their tile?

**Comment by andrei-pavel** [comment]
I've noticed Youtube behaves this way after full-screening and then tiling which is nice.

**Comment by j0hannes** [comment]
Oh, really? I've seen some video players that would maximize to their tile, but Youtube goes completely full screen in my case.

**Comment by andrei-pavel** [comment]
Right, but afterwards if you open a new window or if you press "toggle fullscreen" shortcut or if you press "Grid-Tiling: Refresh" shortcut, the fullscreened Youtube video gets restricted to it's original tile's dimensions, but it occupies the entire space of the tile - without text or empty spaces. I know that's not ideal behavior and that you would want to maybe press a shortcut and fullscreen-tile it directly, I can't answer if that's possible, wait for an official response.

**Comment by j0hannes** [comment]
Yes, that actually works for me too. Would be nice if that could be automated.

**Comment by lingtjien** [comment]
> Yes, that actually works for me too. Would be nice if that could be automated.

I can't really automate that because some people may want to have an application fullscreen, if I automated it, it would mean you could never fullscreen an application. Which is something I do quite often myself when consuming media (and assume others do too).

However, adding such functionality is quite easy if you want too for yourself, I'm just not gonna put it in the repo because it's too specific. You need to add this piece of code, (just before the shortcuts section lines around line `947`)

```
workspace.clientFullScreenSet.connect(function (client)
{
  layout.render();
});
```

**Comment by lingtjien** [comment]
assuming this works for you, otherwise you can open a new ticket
