### ISSUE TITLE
Rotate default layout stacking from column to row?

### ISSUE THREAD

**Issue by kleer001** [lingtjien/Grid-Tiling-Kwin#69]
Right now if I have three windows open they go:

Two stacked vertically in  a column on a side and one in portrait mode (vertical) on the other side in its own column. Like, two on the left and one tall one on the right.

How can I make it so the two (or more) smaller windows stack side to side in their own row and the big one is wide instead of vertical? Like, two on the bottom and one wide one on the top. 

It'd be great to be able to switch the column/row preference. But, I'd be very happy just to know where in your code to make this change so I can alter my local copy of the script. 

I want to do this because I have a big 4K monitor and am using that horizontal window to remote into another computer with two monitors at the same time and then have local things like discord and a terminal going on below them.

**Comment by lingtjien** [comment]
Currently you can't, I only implemented a column based rendering. However, now that I have done the major refactor, it shouldn't be that difficult to implement. Currently a bit busy though, but I'll give it a try when I can find some time.

Out of my curiosity, the reason I originally only implemented column based rendering is because I personally couldn't see the use for having a "landscape" (width > height) size view client, what kind of applications do you use, that benefit from a "landscape" size view?

**Comment by kleer001** [comment]
Awesome, thanks for considering it. 

I'm using Chrome remote desktop on top to remote into my work's two monitors which are 2K while my at home monitor is 4K. That takes up the top half. Then on the bottom half I have Discord running but it's waaaay too wide.

**Comment by andigandi** [comment]
Is there a way to "swap" around opened windows to achieve a layout like this?
```
| 1 |
|2|3|
```

If I understand it correctly, this is exactly what @kleer001 wants, but my motivation is different. I have a normal landscape monitor surrounded by two smaller ones in portrait mode. The current arrangement is perfect for landscape screens. While the proposed layout would result in a ridiculously wide window on the landscape one, the current one gives me such a narrow window on my portrait screens, that they are near useless. I often have "auxiliary" applications on the side screens. For example Discord on top, Easyeffects and Helvum on the bottom. Being able to allow one wide window on top would be a great benefit. But I agree that this is not that useful on landscape screens.

**Comment by lingtjien** [comment]
Oh I tried this once I think but couldn't get it to work easily so I put it in the freezer. I'm assuming you guys already found a different solution for your problem :smile: My apologies for the late reply.

due to plasma 6 release, and big changes to the API. I will close all old inactive tickets, if you still encounter problems then feel free to create a new ticket
