### ISSUE TITLE
Does Grid-Tiling-Kwin work with Plasma Wayland?

### ISSUE THREAD

**Issue by eclipseo** [lingtjien/Grid-Tiling-Kwin#78]
I remember KWin script not working with Wayland, do you know if that changed?

Thanks a lot for your script!

**Comment by lingtjien** [comment]
After a quick google search this is what I found https://bugs.kde.org/show_bug.cgi?id=385595 . It seems to still be open on the bug tracker so... I assume no progress has been made so far... Judging from the comment "Wayland windows are excluded from scripting" I'm guessing it's not gonna work, if they disabled it in KWin itself... Also, I haven't touched wayland yet, maybe I'll give it a try this weekend but I'd doubt it'll work if the maintainer says they disabled the scripting for wayland windows...

On a side note, I don't even use the specific method that they reference in this ticket (because of KWin core design)

**Comment by zzag** [comment]
Wayland windows are exposed to scripting, I overlooked bug 385595 due to its status being "RESOLVED".

**Comment by lingtjien** [comment]
Oh hey, the guy that fixed the KWin bug :)

I'll give it a try and see how much work it is to get it working on Wayland then, but I first need my system to startup in wayland... just tried running it and all I got was a black screen, turned on nvidia-drm kernel module and add the KWin environmental to enable EGLstreams, but no luck (nvidia optimus laptop, so I'll give it a shot if I can get it working with the intel integrated chip, otherwise I'll have to wait for when I can buy a new amd laptop)

**Comment by lingtjien** [comment]
So... after a long time finally got my new laptop with the new AMD 4800U and a working wayland environment 😄 

Refactored, pretty much everything... and now in a more appropriate QML and JS (and this gives me access to most ECMA 6 features, except optional chaining which is in stage 4 of the standard currently) instead of one massive JS file (fun fact, went from total lines 1100 to 850 or something)

I tested all features in both wayland and X11 that I added back one by one. The only thing I didn't test yet is multiscreen support, so if people with multiple monitors could give that some extra attention, that would be great.

Since wayland doesn't support activities yet, the final develop commit will break it (since this commit adds acitivity support) so the wayland branch works for both wayland and X11 but the develop branch only in X11.

Other than that, I'm still missing 2 features, things to figure out, before wayland is usable for me for everyday use, blurring transparent windows (yes, I need my blur... first world problems, I know...) and I still need to figure out why all windows are of the type `normalWindow` in wayland. In X11 I would distinguish normal windows from dialogs based on their type, but in wayland everything seems to be a `normalWindow`.

@zzag how do I know if a window is not a main window but a dialog in wayland? (bonus: how to blur transparent clients?)

so I'll be using the dev branch for now but I'll test new stuff in wayland as well.

**Comment by zzag** [comment]
There is no any straightforward way to determine window type on Wayland. If you want to figure out if a window is a dialog, you could check its transient parent, AbstractClient::transientFor(). I believe transientFor is exposed to the scripting API. As for blur, unfortunately, there is no any simple way to force blur behind translucent windows. An application has to set the blur region using a Wayland protocol, https://invent.kde.org/libraries/plasma-wayland-protocols/-/blob/master/src/protocols/blur.xml.

**Comment by andrei-pavel** [comment]
> multiscreen support

On X11 with Grid-Tiling on develop, I can no longer move a window from one monitor to another with drag and drop. It pops back into place in the previous monitor. But not always in the tiling spot it were before. It respects the place where I drop the window on the new monitor. So if my window was on (1, 1) and I drop it in the new monitor where (3, 3) would be, it returns to old monitor, but on (3, 3). Regardless of whether I have 3x3 windows in the new monitor or none at all.

**Comment by lingtjien** [comment]
@andrei-pavel thx for testing, can you give it another try, gave it a quick test myself this time (I missed one variable while renaming)

@zzag cool and yes `transient` is indeed exposed to the scripting API, so I'm using that now and it seems to work fine for both X11 and wayland. Thank you for the suggestion 😄 (As for blur, I'll try to give kvantum a try and see if I can get blur that way then)

**Comment by lingtjien** [comment]
The whole refactor has been merged back into master and the readme has been updated (instead of a bunch of gifs that were low quality, I just made a mp4 video).

Also, the ignoring has been changed to Regex instead of regular string matching, I mean regex was kinda made for this whole string matching... so now everyone can use all those features as well

(Use the wayland branch for wayland since wayland doesn't support activities yet and the last commit adds activity support and thus breaks wayland)

**Comment by eclipseo** [comment]
> The whole refactor has been merged back into master and the readme has been updated (instead of a bunch of gifs that were low quality, I just made a mp4 video).
> 
> Also, the ignoring has been changed to Regex instead of regular string matching, I mean regex was kinda made for this whole string matching... so now everyone can use all those features as well.
> 
> It has been stable for me after 2 weeks of use, but it was a large refactor, so please report any bugs you may find 
> 
> (Use the wayland branch for wayland since wayland doesn't support activities yet and the last commit adds activity support and thus breaks wayland)

I've tested on Wayland and it doesn't seem to respect the rows/columns setings. I have a setting for 3 columns / 2 rows but all new windows add a new row after the first vertical split.

**Comment by lingtjien** [comment]
I think I fixed it (a one character commit...) please give it another try

**Comment by eclipseo** [comment]
> I think I fixed it (a one character commit...) please give it another try

No bueno, with setting for 3 columns / 2 rows, the tiling stops at 4 windows and open the 5th one in a new desktop.

**Comment by eclipseo** [comment]
Seems to work now, maybe it needed to restart kwin_wayland.
