### ISSUE TITLE
[feature request] toggle windows between tiling and floating

### ISSUE THREAD

**Issue by ysndr** [lingtjien/Grid-Tiling-Kwin#8]
Hej,
first off, I found your plugin to be quite awesome, yet what I am still missing out s having an option to selectively switch windows to/an from floating, like seen in other projects in this regard linke `quarter-tile`.

**Comment by lingtjien** [comment]
I've thought about adding a floating feature (it doesn't require much work) but I could never imagine myself using this feature so I never implemented it.

Could you (or someone else) elaborate on which part of your workflow would benefit from or need a floating window feature?

**Comment by ysndr** [comment]
Well I'm mostly working with an editor in fullscreen mode and a little terminal window floating somewhere always in foreground to keep an eye on progresses, running commands etc. 
This way is quite usefully for me as it doesn't distract me from my main work and does not involve cutting my kinda limited screen space just for having a terminal that could easily float in some corner and does not need such high presence.

It would be great to have this feature in here because that's what's missing to make the switch from quarter-tile which sadly misbehaves in some other areas.

**Comment by IngeniousDox** [comment]
I have found that there are always windows that misbehave. Or windows that I want floating on top (vlc / wine games). Having the ability to float them, and hopefully add them to config that they can be started floating from startup would be very nice.

As another usecase: I also could see me have a grid of terminal windows open. Filled to the max of my screen. And I quickly want to open another terminal floating on top of them somewhere so that I can do something and send it off to another desktop.

As a side option: Having the ability to turn off tiling altogether for a screen or (screen/desktop combo) would be helpful aswell. I have triplescreen with 2560x1440 in mid and 2x 1200x1600 on the side. With AwesomeWM I only enable tiling on my middle screen on most tags. (Perhaps I should have made a new issue for this, since I'm getting out of scope, but I felt I should add it).

**Comment by lingtjien** [comment]
@ysndr So the benefit of having an extra window on top at all times outweighs the negatives of making it slightly more difficult to interact with the windows below. I can live with that.

@IngeniousDox Your first point is the reason I didn't want to implement it as it felt like a cheat to deal with windows that misbehave, this way I forced myself to come up with a solution to misbehaving windows instead of just "it doesn't wanna tile properly, I'll just float it". Which felt like a workaround but not a fix.

Your second argument already has a solution, you can add clients to the list of "ignored clients" or "ignored captions" to prevent those windows from being added to the tiling script. Wine and Overwatch (wine game) are already on that list for example by default

**Comment by lingtjien** [comment]
Should be implemented in the latest commit, you can check it out it in the dev branch. It needs some more testing though and after rewriting some parts of the readme I'll merge it into master :)
