### ISSUE TITLE
BleachBit window randomly opens in a floating mode

### ISSUE THREAD

**Issue by madjoe** [lingtjien/Grid-Tiling-Kwin#88]
How come that the BleachBit main window never gets tiled in my Manjaro KDE Plasma?
I don't have any special window rule, or exclusion for bleachbit, but it manages to run off grid as a floating window.

**Comment by lingtjien** [comment]
I'm guessing because the window type is `specialWindow` or `dialog`

1. type `wm console` in krunner
2. open KWin interactiveconsole
3. in the top bar click `Plasma` and then `KWin`
4. copy paste this snippit
```
let clients = workspace.clientList();
for (var i in clients)
  print(clients.resourceName, clients[i].specialWindow, clients[i].dialog);
```
5. open your program, this case BleachBit
6. press `execute` in the top bar
7. output?

**Comment by madjoe** [comment]
Output:
```
Executing script at Monday, 23 November 2020 17:50:24 CET

Runtime: 4ms

SyntaxError: Parse error
```

Window type of BleachBit is `Normal window`. I just tried it via `Detect Window Properties` inside Window Management > Window Rules.

**Comment by lingtjien** [comment]
Oh yeah... I just discovered a few of those bugs today as well (been refactoring everything for wayland)

I'll commit a small change to the dev branch, give that a try

**Comment by madjoe** [comment]
It's definitely something weird going on here. I just updated your script, restarted my system and opened BleachBit again 10 times in a row: 6 times it opened off grid (as a floating window) and 4 times it opened as a tiled window. :smile: 

This is my config:

_Client Min Space_
**Name**: `Trace Bitmap (Shift+Alt+B), Document Properties (Shift+Ctrl+D), Media viewer, Utility Window, soffice.bin`
**Space**: `1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2`

**Floating clients**: `<empty>`
**Floating captions**: `<empty>`

**Ignored clients**: `wine, overwatch, kcalc, yakuake, audacious, deadbeef, atom, eclipse, code, deja-dup, vlc, gwenview, xsane, xsane-gimp, kodi, kodi-standalone, steam, anydesk, konsole, mpv, libreoffice-math`
**Ignored captions**: `Trace Bitmap (Shift+Alt+B), Document Properties (Shift+Ctrl+D), Media viewer, Utility Window, soffice.bin`

**Comment by lingtjien** [comment]
Are you sure you have the latest version of the `develop` branch running? `Floating clients` and `Floating captions` have been removed for a while now...

Can you check what the resourceName and resourceClass properties of bleachbit are?

Also, after it opens in float, can you still tile it with the global shortcut?

**Comment by madjoe** [comment]
I just did the `git pull origin develop`.

**Whole window class**: bleachbit bleachbit
**Window title**: BleachBit

After it opens in float, the shortcut buttons don't work, since the application "steals" all the keystrokes. I could get it back to grid by dragging the window approx. on the tiled position and it fits and stays there. If I try to drag it away form there, it bounces back to the tiled position.

**Comment by lingtjien** [comment]
If just by dragging the client, it tiles that means that the client itself was already internally tiled by the script so a `Grid-Tiling: Refresh` should tile it also. But if you say that BleachBit steals all the shortcuts then... yeah... I can't do much about that... that's up to the developers of that program...

I'm guessing that when you open BleachBit, and it looks like it starts floating, if you then open any other window that normally tiles (like konsole) on the same virtual desktop, then BleachBit will tile as well. If that is true then it means that BleachBit also sets it's own geometry on startup, some applications like to do that... KWin currently does not allow forcing the geometry, so that's why I made the refresh shortcut so you can tell the application to take a tiled geometry again.

**Comment by madjoe** [comment]
I just opened BleachBit, it opened away from the screen edge and I assumed it's floating. Then I opened another app: Kate and both of those apps suddenly found their own geometry positions inside of grid (both windows were displayed as tiled).

So it's up to BleachBit's custom internal geometry on startup. I may have to report this to BleachBit team, since it should be my culprit (undesired feature). Thanks for helping me to clear this out. :+1:

**Comment by madjoe** [comment]
There's a new follow up to this issue that made the BleachBit developer assume this issue is related to your script: https://github.com/bleachbit/bleachbit/issues/1056#issuecomment-735439087

**Comment by lingtjien** [comment]
Errr... so yeah... he just confirmed what I said... 
> it remembers its position
So yeah BleachBit saved the window geometry on closing and applied that geometry when you open the application. (Kate also does that for example) That's the desired behavior of that application, according to them... So then 2 things can happen

1. bleachbit sets a geometry and I overrule that geometry with a tiled geometry
2. I tell bleachbit to take a tiled geometry and then bleachbit sets a different geometry which may not look tiled

So there's nothing I can do about applications that set their own geometry, KWin does not allow me to force a certain geometry on a client through the scripting interface. That's why I made the `Grid-Tiling: Refresh` shortcut, so you can tell all applications to take a tiled geometry again.

So for all applications that set their own geometry, you have the following options
1. live with it and use the global refresh shortcut, when the application does not take the correct geometry on startup
2. hope the application in question provides a setting that allows you to disable the `remember geometry feature`
3. switch to a WM that does allow forcing a geometry (or hope it becomes available in KWin in the future)

**Comment by madjoe** [comment]
It's not only BleachBit, for some reason I can't open Telegram and Rambox apps in tiled mode. <key>`Super`</key>+<key>`T`</key>, <key>`Super`</key>+<key>`SHIFT`</key>+<key>`T`</key> and <key>`Super`</key>+<key>`R`</key> don't seem to work either. Both windows are opened as Normal mode type. As per Bleachbit, when I dragged the window close to the edge, it snaps into grid, but these two apps don't (they remain as floating windows no matter what I try). Could it be related issue, or is it a new bug?
