### ISSUE TITLE
Side Question: What is your desktop ricing?

### ISSUE THREAD

**Issue by Frick-David** [lingtjien/Grid-Tiling-Kwin#90]
Hey sorry to open an issue on an unrelated note. I saw the pictures showing your great repo at work. I noticed you had an awesome ricing I have not seen before. Would you mind telling me how you got it like that?

Best,
David

**Comment by lingtjien** [comment]
Which parts would you like to know about?

- Top panel is a latte-dock (containing event-calendar, resource monitor, system tray, global menu, virtual desktop switcher), bottom dock is also a latte-dock with my most used apps pinned.
- Background is a collection of images from my favorite digital artist (https://www.instagram.com/aenami.art), that I laid into a shape in `.svg` and then I use my own python script to generate a slideshow of over 20+ at the exact screen resolution. Since it's not my art I don't want to share the final slideshow... since it's not really my work... but it's not that difficult to recreate it using inkscape and her art page.
- Icon theme I build myself using the icons from this project https://github.com/killown/numix-white (I didn't like the behavior of the icon theme and it's not really maintained, so I just cherry picked the icons from that theme that I liked and created my own theme based on that)
- Opacity and blur is done by my other KWin script https://github.com/lingtjien/Opacity-Control-KWin
- Tiling of course this script
